media:
  input: public/assets/images
  output: /assets/images
  categories: [ "image" ]
content:

  - name: home
    label: Home
    type: file
    path: index.md
    fields:
      - { name: layout, type: string, hidden: true, default: basic }
      - { name: title, label: Title, type: string, required: true }
      - { name: body, label: Body, type: rich-text }

  - name: over-ons
    label: Over ons
    type: file
    path: over-ons.md
    fields:
      - { name: layout, type: string, hidden: true, default: gallery }
      - { name: title, label: Title, type: string, required: true }
      - name: photos
        label: Photos
        type: object
        list: true
        fields:
          - name: photo
            label: Photo
            type: image
          - name: size
            label: Size
            type: select
            options:
              values: [ '1/3', '2/3', '3/3' ]
          - name: name
            label: Name
            type: string
          - name: description
            label: Description
            type: string

  - name: repertoire
    label: Repertoire
    type: file
    path: repertoire.md
    fields:
      - { name: layout, type: string, hidden: true, default: repertoire }
      - { name: title, label: Title, type: string, required: true }
      - { name: body, label: Body, type: rich-text }
      - name: songs
        label: Songs
        type: object
        list: true
        fields:
          - name: title
            label: Title
            type: string
          - name: url
            label: URL
            type: string

  - name: fotos
    label: Foto's
    type: file
    path: fotos.md
    fields:
      - { name: layout, type: string, hidden: true, default: gallery }
      - { name: title, label: Title, type: string, required: true }
      - name: photos
        label: Photos
        type: object
        list: true
        fields:
          - name: photo
            label: Photo
            type: image
          - name: size
            label: Size
            type: select
            options:
              values: [ '1/3', '2/3', '3/3' ]
          - name: name
            label: Name
            type: string
          - name: description
            label: Description
            type: string

  - name: agenda
    label: Agenda
    type: file
    path: agenda.md
    fields:
      - { name: layout, type: string, hidden: true, default: basic }
      - { name: title, label: Title, type: string, required: true }
      - { name: body, label: Body, type: rich-text }

  - name: contact
    label: Contact
    type: file
    path: contact.md
    fields:
      - { name: layout, type: string, hidden: true, default: basic }
      - { name: title, label: Title, type: string, required: true }
      - { name: body, label: Body, type: rich-text }
